name: Build Leet Empresas

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Gerar executável
        run: pyinstaller --clean LeetEmpresas.spec

      - name: Compactar
        run: |
          cd dist
          zip -r ../LeetEmpresas-Linux.zip LeetEmpresas

      - uses: actions/upload-artifact@v4
        with:
          name: LeetEmpresas-Linux
          path: LeetEmpresas-Linux.zip

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Gerar executável
        run: pyinstaller --clean LeetEmpresas.spec

      - name: Compactar
        run: |
          Compress-Archive -Path dist/LeetEmpresas -DestinationPath LeetEmpresas-Windows.zip

      - uses: actions/upload-artifact@v4
        with:
          name: LeetEmpresas-Windows
          path: LeetEmpresas-Windows.zip

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Gerar executável
        run: pyinstaller --clean LeetEmpresas.spec

      - name: Compactar
        run: |
          cd dist
          zip -r ../LeetEmpresas-macOS.zip LeetEmpresas

      - uses: actions/upload-artifact@v4
        with:
          name: LeetEmpresas-macOS
          path: LeetEmpresas-macOS.zip

  release:
    needs:
      - linux
      - windows
      - macos

    runs-on: ubuntu-latest

    steps:
      - name: Baixar Linux
        uses: actions/download-artifact@v4
        with:
          name: LeetEmpresas-Linux
          path: release

      - name: Baixar Windows
        uses: actions/download-artifact@v4
        with:
          name: LeetEmpresas-Windows
          path: release

      - name: Baixar macOS
        uses: actions/download-artifact@v4
        with:
          name: LeetEmpresas-macOS
          path: release

      - name: Criar Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            release/LeetEmpresas-Linux.zip
            release/LeetEmpresas-Windows.zip
            release/LeetEmpresas-macOS.zip
